version: '3.3'
services:
  nginx:
    build:
      context: ./nginx
      args:
        environment: ${ENVIRONMENT}
    ports:
      - 80:80
    volumes:
      - ./nginx/html/portal:/usr/share/nginx/html/portal
      - ./nginx/html/www:/usr/share/nginx/html/www

