# https://themes.gohugo.io/aerial/
baseurl      = "http://fu-n.net/"
languageCode = "ja"
countryCode  = "ja"
title        = "fu-n.net"
theme        = "aerial"

[params]
  name      = "fu-n.net"
  about     = "流石だよな、俺ら"
  copyright = "fu-n.net"
  bg_scroll = "" # empty to enable scroll
  #favicon  = "favicon.ico"

#[[params.social]]
#  medium = "Twitter"
#  icon = "twitter"
#  link = "#"
#
#[[params.social]]
#  medium = "Facebook"
#  icon = "facebook"
#  link = "#"
#
#[[params.social]]
#  medium = "Dribbble"
#  icon = "dribbble"
#  link = "#"
#
#[[params.social]]
#  medium = "Github"
#  icon = "github"
#  link = "#"
#
#[[params.social]]
#  medium = "Email"
#  icon = "envelope-o"
#  link = "#"
