# https://themes.gohugo.io/aerial/
baseurl      = "http://localhost/"
languageCode = "ja"
countryCode  = "ja"
title        = "fu-n.net"
theme        = "aerial"

[params]
  name      = "fu-n.net"
  about     = "（　´_ゝ`）流石だよな、俺ら（´<_｀ 　）"
  copyright = "fu-n.net"
  bg_scroll = "" # empty to enable scroll
  #favicon  = "favicon.ico"

# see http://fontawesome.io/icons/
[[params.social]]
  medium = "Portal"
  icon   = "thumbs-o-up"
  link   = "http://portal.localhost/"

#icon = "th"
#[[params.social]]
#  medium = "Twitter"
#  icon = "twitter"
#  link = "https://twitter.com/nunun_jp"
#
#[[params.social]]
#  medium = "Facebook"
#  icon = "facebook"
#  link = "#"
#
#[[params.social]]
#  medium = "Dribbble"
#  icon = "dribbble"
#  link = "#"
#
#[[params.social]]
#  medium = "Github"
#  icon = "github"
#  link = "#"
#
#[[params.social]]
#  medium = "Email"
#  icon = "envelope-o"
#  link = "#"
