# https://themes.gohugo.io/slate/
# write configs and place images into src/static
# then 'sh run.sh hugo' to rebuild local site.
baseurl      = "http://localhost/"
languageCode = "en-us"
title        = "fu-nportal"
theme        = "slate"

[ params ]
#BackgroundImages = [
#  "bg/b1920-000.jpg",
#]
#BackgroundStyle     = "#000000;"
#Favicon             = "favicon.ico"
BackgroundStyle      = "radial-gradient(ellipse farthest-side at center top, #95a3b3 0%, #657383 100%); height:100%;"
OpenLinksInNewWindow = true

# see http://fontawesome.io/icons/
[[ params.nav ]]
name = "activities"
tag = "activities"
icon = "user-circle"

[[ params.nav ]]
name = "codings"
tag = "codings"
icon = "code"

[[ params.nav ]]
name = "devlopments"
tag = "developments"
icon = "wrench"

[[ params.nav ]]
name = "productions"
tag = "productions"
icon = "gift"

[[ params.nav ]]
name = "social"
tag = "social"
icon = "feed"

[[ params.nav ]]
name = "gaming"
tag = "gaming"
icon = "gamepad"

[[ params.nav ]]
name = "favorites"
tag = "favorites"
icon = "star"

