baseurl      = "http://localhost/"
languageCode = "en-us"
title        = "fu-nportal"
theme        = "slate"

[ params ]
BackgroundImages = [
  "bg/b1920-000.jpg",
  "bg/b1920-001.jpg",
  "bg/b1920-002.jpg",
  "bg/b1920-003.jpg",
  "bg/b1920-004.jpg"
]
BackgroundStyle      = "#000000;"
OpenLinksInNewWindow = true
Favicon              = "favicon.ico"

[[ params.nav ]]
name = "favorites"
tag  = "favorite"
icon = "star"
